services:
  # Rust Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aptora-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOST=0.0.0.0
      - PORT=8081
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - KANA_API_KEY=${KANA_API_KEY}
      - KANA_API_BASE_URL=https://perps-tradeapi.kanalabs.io
      - APTOS_API_KEY=${APTOS_API_KEY}
      - APTOS_NETWORK=testnet
      - RUST_LOG=debug
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:4173
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - cargo_cache:/usr/local/cargo/registry
    networks:
      - aptora-network
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Installing Diesel CLI...' &&
        cargo install diesel_cli --version 2.1.1 --no-default-features --features postgres &&
        echo 'Running migrations...' &&
        diesel migration run &&
        echo 'Starting backend server...' &&
        cargo watch -x run
      "

volumes:
  cargo_cache:

networks:
  aptora-network:
    driver: bridge
