[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
dockerContext = "backend"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[env]
HOST = "0.0.0.0"
RUST_LOG = "info"
