[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'echo Starting Aptora Backend... && diesel migration run && echo Starting server... && ./target/release/aptora-backend'"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8081"
RUST_LOG = "info"

